[package]
name = "yum"
version = "0.1.0"
edition = "2021"
authors = ["Yumacide <yumanomics@gmail.com>"]
description = "The compiler for the Yum language"

[dependencies]
logos = "0.12.1"
clap = { version = "3.2.8", features = [ "derive" ]}
anyhow = "1.0.62"
